# Generated by Django 5.0.3 on 2024-04-06 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_review_reviewtext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reviewText',
            new_name='text',
        ),
    ]
